# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Hello from Albanian Xrm'

- script: |
    echo This pipeline configuration will be updated as soon as there will be code to build.
    echo See https://aka.ms/yaml
  displayName: 'Public Promise'
