trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Starting build pipeline!
  displayName: 'Hello from Albanian Xrm'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: release

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))