trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Starting build pipeline!
  displayName: 'Hello from Albanian Xrm'
  
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.x' 

- task: NuGetCommand@2
  displayName: 'Restoring NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: release

- task: NuGetCommand@2
  displayName: 'Creating NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishPipelineArtifact@1
  displayName: 'Publishing NuGet package in Pipeline'
  inputs:
    path: $(System.DefaultWorkingDirectory)/*.nupkg
    artifact: 'NuGet Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))