trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Starting build pipeline!
  displayName: 'Hello from Albanian Xrm'

- powershell: echo "##vso[task.setvariable variable=configuration;isOutput=true]$(IF($env:BRANCH -eq "refs/heads/master"){"Azure Pipelines"}else{"release"})"
  name: MyVars
  env: 
    BRANCH: $(Build.SourceBranch)
  
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.x' 

- task: NuGetCommand@2
  displayName: 'Restoring NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DownloadSecureFile@1
  name: TestSignKey 
  inputs:
    secureFile: 'AlbanianXrm.Pipelines.Tests.snk'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  

- powershell: echo "##vso[task.setvariable variable=Path;isOutput=true]$((get-item $env:SECURE_FILE).Directory.FullName)"
  name: secretFolder
  env:
    Secure_File: $TestSignKey.secureFilePath
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  

- task: CopyFiles@2
  inputs:
    sourceFolder: $(secretFolder.Path)
    contents: 'AlbanianXrm.Pipelines.Tests.snk' 
    targetFolder: 'AlbanianXrm.CrmSvcUtilExtensions.Tests'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: $(MyVars.configuration)

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    testRunTitle: 'Unit Tests'
    platform: 'AnyCPU'
    configuration: $(MyVars.configuration)

- task: NuGetCommand@2
  displayName: 'Creating NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'NuGet Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
